/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipo;

import JPanelsCustom.JPanelCustom;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.awt.Font;
import java.io.InputStream;
import java.awt.Dimension;



/**
 *
 * @author Juanan
 */
public class Fases extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    Cursor mickey;
    Font font_titulos, font_subtitulos;
    String fontName = "/img/GinSSB60.ttf";
    Font font;
    ImageIcon fondo;
    
    
    public Fases() {
        
         Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        
        
          /*/ INICIO FUENTE
         /*/
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_titulos = font.deriveFont(20f).deriveFont(1);
        font_subtitulos = font.deriveFont(40f).deriveFont(1);
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 =  new JPanelCustom("/img/fondo_fases.jpg");
        escuela = new javax.swing.JButton();
        barco = new javax.swing.JButton();
        piramide = new javax.swing.JButton();
        selva = new javax.swing.JButton();
        biblioteca = new javax.swing.JButton();
        titulo_fases = new com.alee.laf.label.WebLabel();
        boton_sonido = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(font_titulos);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        escuela.setFont(font_titulos);
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png"))); // NOI18N
        escuela.setText("La escuela\n de las letras");
        escuela.setBorder(null);
        escuela.setBorderPainted(false);
        escuela.setContentAreaFilled(false);
        escuela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        escuela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        escuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                escuelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                escuelaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                escuelaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                escuelaMouseReleased(evt);
            }
        });
        escuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escuelaActionPerformed(evt);
            }
        });

        barco.setFont(font_titulos);
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png"))); // NOI18N
        barco.setText("Viajando con las sílabas");
        barco.setBorder(null);
        barco.setBorderPainted(false);
        barco.setContentAreaFilled(false);
        barco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barcoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barcoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barcoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                barcoMouseReleased(evt);
            }
        });
        barco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcoActionPerformed(evt);
            }
        });

        piramide.setFont(font_titulos);
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.png"))); // NOI18N
        piramide.setText("Descubriendo las palabras");
        piramide.setBorder(null);
        piramide.setBorderPainted(false);
        piramide.setContentAreaFilled(false);
        piramide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        piramide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        piramide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piramideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piramideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piramideMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                piramideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                piramideMouseReleased(evt);
            }
        });
        piramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piramideActionPerformed(evt);
            }
        });

        selva.setFont(font_titulos);
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Selva.png"))); // NOI18N
        selva.setText("Explorando las frases");
        selva.setBorder(null);
        selva.setBorderPainted(false);
        selva.setContentAreaFilled(false);
        selva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selvaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selvaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selvaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selvaMouseReleased(evt);
            }
        });

        biblioteca.setFont(font_titulos);
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.png"))); // NOI18N
        biblioteca.setText("La biblioteca de textos");
        biblioteca.setBorder(null);
        biblioteca.setBorderPainted(false);
        biblioteca.setContentAreaFilled(false);
        biblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        biblioteca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        biblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bibliotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bibliotecaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bibliotecaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bibliotecaMouseReleased(evt);
            }
        });

        titulo_fases.setForeground(new java.awt.Color(0, 0, 255));
        titulo_fases.setText("¿Dónde quieres jugar hoy?");
        titulo_fases.setFont(font_titulos
        );

        boton_sonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton_sonido.png"))); // NOI18N
        boton_sonido.setBorderPainted(false);
        boton_sonido.setContentAreaFilled(false);
        boton_sonido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_sonidoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_sonidoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(selva))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(escuela))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(boton_sonido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(barco)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(biblioteca))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(piramide))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(titulo_fases, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(piramide))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(boton_sonido)
                        .addGap(18, 18, 18)
                        .addComponent(escuela, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(selva)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(biblioteca)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo_fases, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(barco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escuela.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escuelaActionPerformed

    private void escuelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseEntered
         escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_hover.png")));
    }//GEN-LAST:event_escuelaMouseEntered

    private void escuelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseExited
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png")));
    }//GEN-LAST:event_escuelaMouseExited

    private void barcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcoActionPerformed

    private void barcoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseEntered
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco_hover.png")));
    }//GEN-LAST:event_barcoMouseEntered

    private void barcoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseExited
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png")));
    }//GEN-LAST:event_barcoMouseExited

    private void barcoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMousePressed
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco_press.png")));
    }//GEN-LAST:event_barcoMousePressed

    private void escuelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMousePressed
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_press.png")));
    }//GEN-LAST:event_escuelaMousePressed

    private void barcoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseReleased
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png")));
    }//GEN-LAST:event_barcoMouseReleased

    private void escuelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseReleased
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png")));
    }//GEN-LAST:event_escuelaMouseReleased

    private void piramideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_piramideMouseClicked

    private void piramideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseEntered
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide_hover.png")));
    }//GEN-LAST:event_piramideMouseEntered

    private void piramideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseExited
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.png")));
    }//GEN-LAST:event_piramideMouseExited

    private void piramideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMousePressed
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide_press.png")));
    }//GEN-LAST:event_piramideMousePressed

    private void piramideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseReleased
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.png")));
    }//GEN-LAST:event_piramideMouseReleased

    private void selvaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMouseEntered
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva_hover.png")));
    }//GEN-LAST:event_selvaMouseEntered

    private void selvaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMouseExited
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva.png")));
    }//GEN-LAST:event_selvaMouseExited

    private void selvaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMousePressed
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva_press.png")));
    }//GEN-LAST:event_selvaMousePressed

    private void selvaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMouseReleased
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva.png")));
    }//GEN-LAST:event_selvaMouseReleased

    private void bibliotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseEntered
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca_hover.png")));
    }//GEN-LAST:event_bibliotecaMouseEntered

    private void bibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseExited
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.png")));
    }//GEN-LAST:event_bibliotecaMouseExited

    private void bibliotecaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMousePressed
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca_press.png")));
    }//GEN-LAST:event_bibliotecaMousePressed

    private void bibliotecaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseReleased
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.png")));
    }//GEN-LAST:event_bibliotecaMouseReleased

    private void piramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piramideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piramideActionPerformed

    private void boton_sonidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sonidoMousePressed
        /*if (musica_isActive) {
            boton_sonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton_sonido_pulsado.png")));
        } else {
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido_desactivado_pulsado.png")));
        }*/
    }//GEN-LAST:event_boton_sonidoMousePressed

    private void boton_sonidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sonidoMouseReleased
       /* if (musica_isActive) { //Si está activa -> la desactivamos.
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido_desactivado.png")));
            
            try {
                control.pause();
            } catch (BasicPlayerException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido.png")));
           
            try {
                if (control_pausado) {
                    control.play();
                } else {
                    control.resume();
                }
                control_pausado = false;
            } catch (BasicPlayerException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(musica_isActive){
            musica_isActive = false;
        }else{
            musica_isActive = true;
        }*/
    }//GEN-LAST:event_boton_sonidoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fases().setVisible(true);
                ////////////////////////////////
                
               
                
                
               
            ////////////////////////////    
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barco;
    private javax.swing.JButton biblioteca;
    private javax.swing.JButton boton_sonido;
    private javax.swing.JButton escuela;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton piramide;
    private javax.swing.JButton selva;
    private com.alee.laf.label.WebLabel titulo_fases;
    // End of variables declaration//GEN-END:variables
}
