/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipo;

import JPanelsCustom.JPanelCustom;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.awt.Font;
import java.io.InputStream;
import java.awt.Dimension;



/**
 *
 * @author Juanan
 */
public class Fases extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    Cursor mickey;
    Font font_titulos, font_subtitulos;
    String fontName = "/img/palmemim.ttf";
    Font font;
    ImageIcon fondo;
    
    
    public Fases() {
        
         Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        
        
          /*/ INICIO FUENTE
         /*/
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_titulos = font.deriveFont(25f).deriveFont(1);
        font_subtitulos = font.deriveFont(40f).deriveFont(1);
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        panel_fases =  new JPanelCustom("/img/fondoFases.png");
        escuela = new javax.swing.JButton();
        barco = new javax.swing.JButton();
        piramide = new javax.swing.JButton();
        selva = new javax.swing.JButton();
        biblioteca = new javax.swing.JButton();
        titulo_fases = new com.alee.laf.label.WebLabel();
        boton_sonido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fases.setFont(font_titulos);
        panel_fases.setMaximumSize(new java.awt.Dimension(800, 600));
        panel_fases.setMinimumSize(new java.awt.Dimension(800, 600));
        panel_fases.setPreferredSize(new java.awt.Dimension(800, 600));

        escuela.setFont(font_titulos);
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png"))); // NOI18N
        escuela.setBorder(null);
        escuela.setBorderPainted(false);
        escuela.setContentAreaFilled(false);
        escuela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        escuela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        escuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                escuelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                escuelaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                escuelaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                escuelaMouseReleased(evt);
            }
        });
        escuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escuelaActionPerformed(evt);
            }
        });

        barco.setFont(font_titulos);
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png"))); // NOI18N
        barco.setBorder(null);
        barco.setBorderPainted(false);
        barco.setContentAreaFilled(false);
        barco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barcoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barcoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barcoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                barcoMouseReleased(evt);
            }
        });
        barco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcoActionPerformed(evt);
            }
        });

        piramide.setFont(font_titulos);
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.png"))); // NOI18N
        piramide.setBorder(null);
        piramide.setBorderPainted(false);
        piramide.setContentAreaFilled(false);
        piramide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        piramide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        piramide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piramideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piramideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piramideMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                piramideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                piramideMouseReleased(evt);
            }
        });
        piramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piramideActionPerformed(evt);
            }
        });

        selva.setFont(font_titulos);
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Selva.png"))); // NOI18N
        selva.setBorder(null);
        selva.setBorderPainted(false);
        selva.setContentAreaFilled(false);
        selva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selvaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selvaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selvaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selvaMouseReleased(evt);
            }
        });

        biblioteca.setFont(font_titulos);
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.png"))); // NOI18N
        biblioteca.setBorder(null);
        biblioteca.setBorderPainted(false);
        biblioteca.setContentAreaFilled(false);
        biblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        biblioteca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        biblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bibliotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bibliotecaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bibliotecaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bibliotecaMouseReleased(evt);
            }
        });

        titulo_fases.setForeground(new java.awt.Color(0, 0, 255));
        titulo_fases.setText("¿Dónde quieres jugar hoy?");
        titulo_fases.setFont(new java.awt.Font("PalMeMim", 1, 36)); // NOI18N

        boton_sonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton_sonido.png"))); // NOI18N
        boton_sonido.setBorderPainted(false);
        boton_sonido.setContentAreaFilled(false);
        boton_sonido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_sonidoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_sonidoMouseReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("PalMeMim", 1, 30)); // NOI18N
        jLabel1.setText("<html><center>La escuela de <br> las letras</center></html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("PalMeMim", 1, 30)); // NOI18N
        jLabel2.setText("<html><center>Viajando con<br> las sílabas</center></html>");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("PalMeMim", 1, 30)); // NOI18N
        jLabel3.setText("<html><center>Descubriendo las<br> palabras</center></html>");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("PalMeMim", 1, 30)); // NOI18N
        jLabel4.setText("La biblioteca de textos");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("PalMeMim", 1, 30)); // NOI18N
        jLabel5.setText("Explorando las frases");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout panel_fasesLayout = new javax.swing.GroupLayout(panel_fases);
        panel_fases.setLayout(panel_fasesLayout);
        panel_fasesLayout.setHorizontalGroup(
            panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fasesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(escuela))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(barco)
                                .addGap(335, 335, 335))
                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(boton_sonido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(titulo_fases, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panel_fasesLayout.createSequentialGroup()
                .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(selva))
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fasesLayout.createSequentialGroup()
                        .addComponent(biblioteca)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fasesLayout.createSequentialGroup()
                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(piramide)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        panel_fasesLayout.setVerticalGroup(
            panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fasesLayout.createSequentialGroup()
                .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(panel_fasesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                .addComponent(boton_sonido)
                                .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fasesLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(barco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_fasesLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                                .addComponent(escuela, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                                .addComponent(piramide)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(titulo_fases, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(biblioteca)
                            .addComponent(selva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_fasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fasesLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fases, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fases, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_sonidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sonidoMouseReleased
        /* if (musica_isActive) { //Si está activa -> la desactivamos.
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido_desactivado.png")));

            try {
                control.pause();
            } catch (BasicPlayerException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido.png")));

            try {
                if (control_pausado) {
                    control.play();
                } else {
                    control.resume();
                }
                control_pausado = false;
            } catch (BasicPlayerException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(musica_isActive){
            musica_isActive = false;
        }else{
            musica_isActive = true;
        }*/
    }//GEN-LAST:event_boton_sonidoMouseReleased

    private void boton_sonidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sonidoMousePressed
        /*if (musica_isActive) {
            boton_sonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton_sonido_pulsado.png")));
        } else {
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido_desactivado_pulsado.png")));
        }*/
    }//GEN-LAST:event_boton_sonidoMousePressed

    private void bibliotecaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseReleased
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.png")));
    }//GEN-LAST:event_bibliotecaMouseReleased

    private void bibliotecaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMousePressed
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca_press.png")));
    }//GEN-LAST:event_bibliotecaMousePressed

    private void bibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseExited
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.png")));
    }//GEN-LAST:event_bibliotecaMouseExited

    private void bibliotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseEntered
        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca_hover.png")));
    }//GEN-LAST:event_bibliotecaMouseEntered

    private void selvaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMouseReleased
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva.png")));
    }//GEN-LAST:event_selvaMouseReleased

    private void selvaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMousePressed
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva_press.png")));
    }//GEN-LAST:event_selvaMousePressed

    private void selvaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMouseExited
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva.png")));
    }//GEN-LAST:event_selvaMouseExited

    private void selvaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selvaMouseEntered
        selva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selva_hover.png")));
    }//GEN-LAST:event_selvaMouseEntered

    private void piramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piramideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piramideActionPerformed

    private void piramideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseReleased
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.png")));
    }//GEN-LAST:event_piramideMouseReleased

    private void piramideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMousePressed
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide_press.png")));
    }//GEN-LAST:event_piramideMousePressed

    private void piramideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseExited
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.png")));
    }//GEN-LAST:event_piramideMouseExited

    private void piramideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseEntered
        piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide_hover.png")));
    }//GEN-LAST:event_piramideMouseEntered

    private void piramideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piramideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_piramideMouseClicked

    private void barcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcoActionPerformed

    private void barcoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseReleased
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png")));
    }//GEN-LAST:event_barcoMouseReleased

    private void barcoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMousePressed
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco_press.png")));
    }//GEN-LAST:event_barcoMousePressed

    private void barcoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseExited
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png")));
    }//GEN-LAST:event_barcoMouseExited

    private void barcoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseEntered
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco_hover.png")));
    }//GEN-LAST:event_barcoMouseEntered

    private void escuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escuelaActionPerformed

    private void escuelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseReleased
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png")));
    }//GEN-LAST:event_escuelaMouseReleased

    private void escuelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMousePressed
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_press.png")));
    }//GEN-LAST:event_escuelaMousePressed

    private void escuelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseExited
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png")));
    }//GEN-LAST:event_escuelaMouseExited

    private void escuelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseEntered
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_hover.png")));
    }//GEN-LAST:event_escuelaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fases().setVisible(true);
                ////////////////////////////////
                
               
                
                
               
            ////////////////////////////    
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barco;
    private javax.swing.JButton biblioteca;
    private javax.swing.JButton boton_sonido;
    private javax.swing.JButton escuela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel_fases;
    private javax.swing.JButton piramide;
    private javax.swing.JButton selva;
    private com.alee.laf.label.WebLabel titulo_fases;
    // End of variables declaration//GEN-END:variables
}
