/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipo;

import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.awt.Font;
import java.io.InputStream;
import java.awt.Dimension;

/**
 *
 * @author Juanan
 */
public class Fases extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    Cursor mickey;
    Font font_titulos, font_subtitulos;
    String fontName = "/img/GinSSB60.ttf";
    Font font;
    ImageIcon fondo;
    
    
    public Fases() {
        
         Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        
        
          /*/ INICIO FUENTE
         /*/
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_titulos = font.deriveFont(20f).deriveFont(1);
        font_subtitulos = font.deriveFont(40f).deriveFont(1);
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escuela = new javax.swing.JButton();
        barco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(font_titulos);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        escuela.setFont(font_titulos);
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png"))); // NOI18N
        escuela.setText("La escuela\n de las letras");
        escuela.setBorder(null);
        escuela.setBorderPainted(false);
        escuela.setContentAreaFilled(false);
        escuela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        escuela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        escuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                escuelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                escuelaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                escuelaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                escuelaMouseReleased(evt);
            }
        });
        escuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escuelaActionPerformed(evt);
            }
        });

        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png"))); // NOI18N
        barco.setText("Viajando con las sílabas");
        barco.setBorder(null);
        barco.setBorderPainted(false);
        barco.setContentAreaFilled(false);
        barco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barcoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barcoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barcoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                barcoMouseReleased(evt);
            }
        });
        barco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(escuela)
                .addGap(97, 97, 97)
                .addComponent(barco)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(barco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(escuela, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        escuela.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escuelaActionPerformed

    private void escuelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseEntered
         escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_hover.png")));
    }//GEN-LAST:event_escuelaMouseEntered

    private void escuelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseExited
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png")));
    }//GEN-LAST:event_escuelaMouseExited

    private void barcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcoActionPerformed

    private void barcoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseEntered
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco_hover.png")));
    }//GEN-LAST:event_barcoMouseEntered

    private void barcoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseExited
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png")));
    }//GEN-LAST:event_barcoMouseExited

    private void barcoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMousePressed
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco_click.png")));
    }//GEN-LAST:event_barcoMousePressed

    private void escuelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMousePressed
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_click.png")));
    }//GEN-LAST:event_escuelaMousePressed

    private void barcoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcoMouseReleased
        barco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barco.png")));
    }//GEN-LAST:event_barcoMouseReleased

    private void escuelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escuelaMouseReleased
        escuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school.png")));
    }//GEN-LAST:event_escuelaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fases().setVisible(true);
                ////////////////////////////////
                
               
                
                
               
            ////////////////////////////    
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barco;
    private javax.swing.JButton escuela;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
