/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipo;

import JPanelsCustom.JPanelCustom;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.InputStream;
import javax.swing.ImageIcon;
/**
 *
 * @author oscarmirandabravo
 */
public class NivelesFase3 extends javax.swing.JFrame {
    Cursor mickey;
    Font font_boton_niveles, font_titulo_niveles;
    String fontName = "/img/GinSSB60.ttf";
    Font font;

    /**
     * Creates new form NivelesFase1
     */
    
    
    public NivelesFase3() {
        Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        /* INICIO FUENTE
         */
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_boton_niveles = font.deriveFont(30f).deriveFont(1);
        font_titulo_niveles = font.deriveFont(50f).deriveFont(1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fase3 = new JPanelCustom("/img/fondoPiramide.png");
        nivel1fase3 = new javax.swing.JButton();
        nivel2fase3 = new javax.swing.JButton();
        nivel3fase3 = new javax.swing.JButton();
        nivel4fase3 = new javax.swing.JButton();
        TituloFase3 = new com.alee.laf.label.WebLabel();
        backFase3 = new javax.swing.JButton();
        homeFase3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(font_titulo_niveles);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        Fase3.setBackground(new java.awt.Color(204, 255, 204));
        Fase3.setFont(font_titulo_niveles);
        Fase3.setMaximumSize(new java.awt.Dimension(800, 600));
        Fase3.setMinimumSize(new java.awt.Dimension(800, 600));

        nivel1fase3.setFont(font_boton_niveles);
        nivel1fase3.setForeground(new java.awt.Color(255, 255, 255));
        nivel1fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_green.png"))); // NOI18N
        nivel1fase3.setText("Nivel 1");
        nivel1fase3.setBorderPainted(false);
        nivel1fase3.setContentAreaFilled(false);
        nivel1fase3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel1fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel1fase3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel1fase3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel1fase3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel1fase3MouseEntered(evt);
            }
        });

        nivel2fase3.setFont(font_boton_niveles);
        nivel2fase3.setForeground(new java.awt.Color(255, 255, 255));
        nivel2fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_orange.png"))); // NOI18N
        nivel2fase3.setText("Nivel 2");
        nivel2fase3.setBorderPainted(false);
        nivel2fase3.setContentAreaFilled(false);
        nivel2fase3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel2fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel2fase3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel2fase3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel2fase3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel2fase3MouseEntered(evt);
            }
        });
        nivel2fase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel2fase3ActionPerformed(evt);
            }
        });

        nivel3fase3.setFont(font_boton_niveles);
        nivel3fase3.setForeground(new java.awt.Color(255, 255, 255));
        nivel3fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_yellow.png"))); // NOI18N
        nivel3fase3.setText("Nivel 3");
        nivel3fase3.setBorderPainted(false);
        nivel3fase3.setContentAreaFilled(false);
        nivel3fase3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel3fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel3fase3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel3fase3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel3fase3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel3fase3MouseEntered(evt);
            }
        });
        nivel3fase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel3fase3ActionPerformed(evt);
            }
        });

        nivel4fase3.setFont(font_boton_niveles);
        nivel4fase3.setForeground(new java.awt.Color(255, 255, 255));
        nivel4fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_blue.png"))); // NOI18N
        nivel4fase3.setText("Nivel 4");
        nivel4fase3.setBorderPainted(false);
        nivel4fase3.setContentAreaFilled(false);
        nivel4fase3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel4fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel4fase3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel4fase3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel4fase3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel4fase3MouseEntered(evt);
            }
        });
        nivel4fase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel4fase3ActionPerformed(evt);
            }
        });

        TituloFase3.setForeground(new java.awt.Color(0, 51, 255));
        TituloFase3.setText("Escoge un nivel");
        TituloFase3.setFont(font_titulo_niveles);

        backFase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        backFase3.setBorderPainted(false);
        backFase3.setContentAreaFilled(false);

        homeFase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        homeFase3.setBorderPainted(false);
        homeFase3.setContentAreaFilled(false);
        homeFase3.setEnabled(false);
        homeFase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeFase3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fase3Layout = new javax.swing.GroupLayout(Fase3);
        Fase3.setLayout(Fase3Layout);
        Fase3Layout.setHorizontalGroup(
            Fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fase3Layout.createSequentialGroup()
                .addGroup(Fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Fase3Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(Fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nivel1fase3)
                            .addComponent(nivel3fase3))
                        .addGap(109, 109, 109)
                        .addComponent(nivel2fase3))
                    .addGroup(Fase3Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(TituloFase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fase3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backFase3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeFase3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nivel4fase3)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        Fase3Layout.setVerticalGroup(
            Fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fase3Layout.createSequentialGroup()
                .addGroup(Fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fase3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TituloFase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(nivel1fase3)
                        .addGap(48, 48, 48)
                        .addComponent(nivel3fase3)
                        .addGap(31, 31, 31)
                        .addGroup(Fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backFase3)
                            .addComponent(homeFase3)))
                    .addGroup(Fase3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(nivel2fase3)
                        .addGap(70, 70, 70)
                        .addComponent(nivel4fase3)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fase3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fase3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(298, 298, 298))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivel1fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase3MouseEntered
        // TODO add your handling cocircle_blue_pulsadode here:
        nivel1fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_green_hover.png")));
    }//GEN-LAST:event_nivel1fase3MouseEntered

    private void nivel1fase3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase3MouseExited
        // TODO add your handling code here:
        nivel1fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_green.png")));
    }//GEN-LAST:event_nivel1fase3MouseExited

    private void nivel1fase3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase3MousePressed
        // TODO add your handling code here:
        nivel1fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_green_pulsado.png")));
    }//GEN-LAST:event_nivel1fase3MousePressed

    private void nivel1fase3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase3MouseReleased
        // TODO add your handling code here:
        nivel1fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_green.png")));
    }//GEN-LAST:event_nivel1fase3MouseReleased

    private void nivel2fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase3MouseEntered
        // TODO add your handling code here:
        nivel2fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_orange_hover.png")));
    }//GEN-LAST:event_nivel2fase3MouseEntered

    private void nivel2fase3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase3MouseExited
        // TODO add your handling code here:
        nivel2fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_orange.png")));
    }//GEN-LAST:event_nivel2fase3MouseExited

    private void nivel2fase3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase3MousePressed
        // TODO add your handling code here:
        nivel2fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_orange_pulsado.png")));
    }//GEN-LAST:event_nivel2fase3MousePressed

    private void nivel2fase3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase3MouseReleased
        // TODO add your handling code here:
        nivel2fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_orange.png")));
    }//GEN-LAST:event_nivel2fase3MouseReleased

    private void nivel3fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase3MouseEntered
        // TODO add your handling code here:
        nivel3fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_yellow_hover.png")));
    }//GEN-LAST:event_nivel3fase3MouseEntered

    private void nivel3fase3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase3MouseExited
        // TODO add your handling code here:
        nivel3fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_yellow.png")));
    }//GEN-LAST:event_nivel3fase3MouseExited

    private void nivel3fase3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase3MousePressed
        // TODO add your handling code here:
        nivel3fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_yellow_pulsado.png")));
    }//GEN-LAST:event_nivel3fase3MousePressed

    private void nivel3fase3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase3MouseReleased
        // TODO add your handling code here:
        nivel3fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_yellow.png")));
    }//GEN-LAST:event_nivel3fase3MouseReleased

    private void nivel4fase3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel4fase3MouseEntered
        // TODO add your handling code here:
        nivel4fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_blue_hover.png")));
    }//GEN-LAST:event_nivel4fase3MouseEntered

    private void nivel4fase3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel4fase3MouseExited
        // TODO add your handling code here:
        nivel4fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_blue.png")));
    }//GEN-LAST:event_nivel4fase3MouseExited

    private void nivel4fase3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel4fase3MouseReleased
        // TODO add your handling code here:
        nivel4fase3.setIcon(new ImageIcon(getClass().getResource("/img/circle_blue.png")));
    }//GEN-LAST:event_nivel4fase3MouseReleased

    private void nivel4fase3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel4fase3MousePressed
        // TODO add your handling code here:
        nivel4fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_blue_pulsado.png")));
    }//GEN-LAST:event_nivel4fase3MousePressed

    private void nivel3fase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel3fase3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivel3fase3ActionPerformed

    private void nivel2fase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel2fase3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivel2fase3ActionPerformed

    private void nivel4fase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel4fase3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivel4fase3ActionPerformed

    private void homeFase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeFase3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeFase3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelesFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelesFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelesFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelesFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelesFase3().setVisible(true);
            }
        });
    }

     private javax.swing.JButton boton_sonido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fase3;
    private com.alee.laf.label.WebLabel TituloFase3;
    private javax.swing.JButton backFase3;
    private javax.swing.JButton homeFase3;
    private javax.swing.JButton nivel1fase3;
    private javax.swing.JButton nivel2fase3;
    private javax.swing.JButton nivel3fase3;
    private javax.swing.JButton nivel4fase3;
    // End of variables declaration//GEN-END:variables
}
