/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipo;

import JPanelsCustom.JPanelCustom;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.InputStream;
import javax.swing.ImageIcon;
/**
 *
 * @author oscarmirandabravo
 */
public class NivelesFase2 extends javax.swing.JFrame {
    Cursor mickey;
    Font font_boton_niveles, font_titulo_niveles;
    String fontName = "/img/GinSSB60.ttf";
    Font font;

    /**
     * Creates new form NivelesFase1
     */
    
    
    public NivelesFase2() {
        Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        /* INICIO FUENTE
         */
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_boton_niveles = font.deriveFont(30f).deriveFont(1);
        font_titulo_niveles = font.deriveFont(50f).deriveFont(1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fase2 = new JPanelCustom("/img/fondoBarco.png");
        nivel1fase2 = new javax.swing.JButton();
        nivel2fase2 = new javax.swing.JButton();
        nivel3fase2 = new javax.swing.JButton();
        TituloFase2 = new com.alee.laf.label.WebLabel();
        backFase2 = new javax.swing.JButton();
        homeFase2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panel_fase2.setBackground(new java.awt.Color(204, 255, 204));
        panel_fase2.setMaximumSize(new java.awt.Dimension(800, 600));
        panel_fase2.setMinimumSize(new java.awt.Dimension(800, 600));

        nivel1fase2.setFont(font_boton_niveles);
        nivel1fase2.setForeground(new java.awt.Color(255, 255, 255));
        nivel1fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_red.png"))); // NOI18N
        nivel1fase2.setText("Nivel 1");
        nivel1fase2.setBorderPainted(false);
        nivel1fase2.setContentAreaFilled(false);
        nivel1fase2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel1fase2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel1fase2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel1fase2MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel1fase2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel1fase2MouseEntered(evt);
            }
        });
        nivel1fase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel1fase2ActionPerformed(evt);
            }
        });

        nivel2fase2.setFont(font_boton_niveles);
        nivel2fase2.setForeground(new java.awt.Color(255, 255, 255));
        nivel2fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_grey.png"))); // NOI18N
        nivel2fase2.setText("Nivel 2");
        nivel2fase2.setBorderPainted(false);
        nivel2fase2.setContentAreaFilled(false);
        nivel2fase2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel2fase2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel2fase2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel2fase2MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel2fase2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel2fase2MouseEntered(evt);
            }
        });

        nivel3fase2.setFont(font_boton_niveles);
        nivel3fase2.setForeground(new java.awt.Color(255, 255, 255));
        nivel3fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_orange.png"))); // NOI18N
        nivel3fase2.setText("Nivel 3");
        nivel3fase2.setBorderPainted(false);
        nivel3fase2.setContentAreaFilled(false);
        nivel3fase2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nivel3fase2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nivel3fase2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nivel3fase2MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nivel3fase2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nivel3fase2MouseEntered(evt);
            }
        });
        nivel3fase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel3fase2ActionPerformed(evt);
            }
        });

        TituloFase2.setForeground(new java.awt.Color(0, 51, 255));
        TituloFase2.setText("Escoge un nivel");
        TituloFase2.setFont(font_titulo_niveles);

        backFase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        backFase2.setBorderPainted(false);
        backFase2.setContentAreaFilled(false);
        backFase2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backFase2MouseClicked(evt);
            }
        });

        homeFase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        homeFase2.setBorderPainted(false);
        homeFase2.setContentAreaFilled(false);
        homeFase2.setEnabled(false);
        homeFase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeFase2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fase2Layout = new javax.swing.GroupLayout(panel_fase2);
        panel_fase2.setLayout(panel_fase2Layout);
        panel_fase2Layout.setHorizontalGroup(
            panel_fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fase2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(nivel1fase2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(nivel2fase2)
                .addGap(148, 148, 148))
            .addGroup(panel_fase2Layout.createSequentialGroup()
                .addGroup(panel_fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fase2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backFase2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeFase2)
                        .addGap(140, 140, 140)
                        .addComponent(nivel3fase2))
                    .addGroup(panel_fase2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(TituloFase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_fase2Layout.setVerticalGroup(
            panel_fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fase2Layout.createSequentialGroup()
                .addGroup(panel_fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fase2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(TituloFase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(nivel1fase2))
                    .addGroup(panel_fase2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(nivel2fase2)))
                .addGroup(panel_fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fase2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(nivel3fase2)
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fase2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backFase2)
                            .addComponent(homeFase2))
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fase2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fase2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivel1fase2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase2MouseEntered
        // TODO add your handling cocircle_blue_pulsadode here:
        nivel1fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_red_hover.png")));
    }//GEN-LAST:event_nivel1fase2MouseEntered

    private void nivel1fase2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase2MouseExited
        // TODO add your handling code here:
        nivel1fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_red.png")));
    }//GEN-LAST:event_nivel1fase2MouseExited

    private void nivel1fase2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase2MousePressed
        // TODO add your handling code here:
        nivel1fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_red_pulsado.png")));
    }//GEN-LAST:event_nivel1fase2MousePressed

    private void nivel1fase2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel1fase2MouseReleased
        // TODO add your handling code here:
        nivel1fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_red.png")));
    }//GEN-LAST:event_nivel1fase2MouseReleased

    private void nivel2fase2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase2MouseEntered
        // TODO add your handling code here:
        nivel2fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_grey_hover.png")));
    }//GEN-LAST:event_nivel2fase2MouseEntered

    private void nivel2fase2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase2MouseExited
        // TODO add your handling code here:
        nivel2fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_grey.png")));
    }//GEN-LAST:event_nivel2fase2MouseExited

    private void nivel2fase2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase2MousePressed
        // TODO add your handling code here:
        nivel2fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_grey_pulsado.png")));
    }//GEN-LAST:event_nivel2fase2MousePressed

    private void nivel2fase2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel2fase2MouseReleased
        // TODO add your handling code here:
        nivel2fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_grey.png")));
    }//GEN-LAST:event_nivel2fase2MouseReleased

    private void nivel3fase2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase2MouseEntered
        // TODO add your handling code here:
        nivel3fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_orange_hover.png")));
    }//GEN-LAST:event_nivel3fase2MouseEntered

    private void nivel3fase2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase2MouseExited
        // TODO add your handling code here:
        nivel3fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_orange.png")));
    }//GEN-LAST:event_nivel3fase2MouseExited

    private void nivel3fase2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase2MousePressed
        // TODO add your handling code here:
        nivel3fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle_orange_pulsado.png")));
    }//GEN-LAST:event_nivel3fase2MousePressed

    private void nivel3fase2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3fase2MouseReleased
        // TODO add your handling code here:
        nivel3fase2.setIcon(new ImageIcon(getClass().getResource("/img/circle_orange.png")));
    }//GEN-LAST:event_nivel3fase2MouseReleased

    private void nivel1fase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel1fase2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivel1fase2ActionPerformed

    private void nivel3fase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel3fase2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivel3fase2ActionPerformed

    private void backFase2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backFase2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backFase2MouseClicked

    private void homeFase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeFase2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeFase2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelesFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelesFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelesFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelesFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelesFase2().setVisible(true);
            }
        });
    }

     private javax.swing.JButton boton_sonido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.label.WebLabel TituloFase2;
    private javax.swing.JButton backFase2;
    private javax.swing.JButton homeFase2;
    private javax.swing.JButton nivel1fase2;
    private javax.swing.JButton nivel2fase2;
    private javax.swing.JButton nivel3fase2;
    private javax.swing.JPanel panel_fase2;
    // End of variables declaration//GEN-END:variables
}
