
package ipo;

/**
 *
 * @author Juanan
 */

import JPanelsCustom.JPanelCustom;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.awt.Font;
import java.io.InputStream;
import java.awt.Dimension;

public class Password2 extends javax.swing.JFrame {

    Cursor mickey;
    Font font_titulos, font_subtitulos;
    String fontName = "/img/GinSSB60.ttf";
    Font font;
    ImageIcon fondo;
    
    public Password2() {
        
         Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        
        
          /*/ INICIO FUENTE
         /*/
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_titulos = font.deriveFont(20f).deriveFont(1);
        font_subtitulos = font.deriveFont(40f).deriveFont(1);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanelCustom("/img/fondo_password2.jpg");
        globo1 = new javax.swing.JButton();
        globo2 = new javax.swing.JButton();
        globo3 = new javax.swing.JButton();
        globo4 = new javax.swing.JButton();
        globo5 = new javax.swing.JButton();
        globo6 = new javax.swing.JButton();
        globo7 = new javax.swing.JButton();
        globo8 = new javax.swing.JButton();
        globo9 = new javax.swing.JButton();
        globo10 = new javax.swing.JButton();
        globo11 = new javax.swing.JButton();
        globo12 = new javax.swing.JButton();
        globo13 = new javax.swing.JButton();
        globo14 = new javax.swing.JButton();
        globo15 = new javax.swing.JButton();
        globo16 = new javax.swing.JButton();
        globo17 = new javax.swing.JButton();
        globo18 = new javax.swing.JButton();
        globo19 = new javax.swing.JButton();
        globo20 = new javax.swing.JButton();
        globo21 = new javax.swing.JButton();
        globo22 = new javax.swing.JButton();
        globo23 = new javax.swing.JButton();
        globo24 = new javax.swing.JButton();
        globo25 = new javax.swing.JButton();
        titulo_password2 = new com.alee.laf.label.WebLabel();
        boton_sonido = new javax.swing.JButton();
        back_pass_infantil = new javax.swing.JButton();
        home_pass_infantil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        globo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo1.png"))); // NOI18N
        globo1.setBorder(null);
        globo1.setBorderPainted(false);
        globo1.setContentAreaFilled(false);
        globo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo1MouseReleased(evt);
            }
        });

        globo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo2.png"))); // NOI18N
        globo2.setBorder(null);
        globo2.setBorderPainted(false);
        globo2.setContentAreaFilled(false);
        globo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo2MouseReleased(evt);
            }
        });

        globo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo3.png"))); // NOI18N
        globo3.setBorder(null);
        globo3.setBorderPainted(false);
        globo3.setContentAreaFilled(false);
        globo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo3MouseReleased(evt);
            }
        });

        globo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo4.png"))); // NOI18N
        globo4.setBorder(null);
        globo4.setBorderPainted(false);
        globo4.setContentAreaFilled(false);
        globo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo4MouseReleased(evt);
            }
        });

        globo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo5.png"))); // NOI18N
        globo5.setBorder(null);
        globo5.setBorderPainted(false);
        globo5.setContentAreaFilled(false);
        globo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo5MouseReleased(evt);
            }
        });

        globo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo6.png"))); // NOI18N
        globo6.setBorder(null);
        globo6.setBorderPainted(false);
        globo6.setContentAreaFilled(false);
        globo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo6MouseReleased(evt);
            }
        });

        globo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo7.png"))); // NOI18N
        globo7.setBorder(null);
        globo7.setBorderPainted(false);
        globo7.setContentAreaFilled(false);
        globo7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo7MouseReleased(evt);
            }
        });

        globo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo8.png"))); // NOI18N
        globo8.setBorder(null);
        globo8.setBorderPainted(false);
        globo8.setContentAreaFilled(false);
        globo8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo8MouseReleased(evt);
            }
        });

        globo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo9.png"))); // NOI18N
        globo9.setBorder(null);
        globo9.setBorderPainted(false);
        globo9.setContentAreaFilled(false);
        globo9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo9MouseReleased(evt);
            }
        });

        globo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo10.png"))); // NOI18N
        globo10.setBorder(null);
        globo10.setBorderPainted(false);
        globo10.setContentAreaFilled(false);
        globo10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo10MouseReleased(evt);
            }
        });

        globo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo11.png"))); // NOI18N
        globo11.setBorder(null);
        globo11.setBorderPainted(false);
        globo11.setContentAreaFilled(false);
        globo11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo11MouseReleased(evt);
            }
        });

        globo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo12.png"))); // NOI18N
        globo12.setBorder(null);
        globo12.setBorderPainted(false);
        globo12.setContentAreaFilled(false);
        globo12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo12MouseReleased(evt);
            }
        });

        globo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo13.png"))); // NOI18N
        globo13.setBorder(null);
        globo13.setBorderPainted(false);
        globo13.setContentAreaFilled(false);
        globo13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo13MouseReleased(evt);
            }
        });

        globo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo14.png"))); // NOI18N
        globo14.setBorder(null);
        globo14.setBorderPainted(false);
        globo14.setContentAreaFilled(false);
        globo14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo14MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo14MouseReleased(evt);
            }
        });

        globo15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo15.png"))); // NOI18N
        globo15.setBorder(null);
        globo15.setBorderPainted(false);
        globo15.setContentAreaFilled(false);
        globo15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo15MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo15MouseReleased(evt);
            }
        });

        globo16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo16.png"))); // NOI18N
        globo16.setBorder(null);
        globo16.setBorderPainted(false);
        globo16.setContentAreaFilled(false);
        globo16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo16MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo16MouseReleased(evt);
            }
        });

        globo17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo17.png"))); // NOI18N
        globo17.setBorder(null);
        globo17.setBorderPainted(false);
        globo17.setContentAreaFilled(false);
        globo17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo17MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo17MouseReleased(evt);
            }
        });

        globo18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo18.png"))); // NOI18N
        globo18.setBorder(null);
        globo18.setBorderPainted(false);
        globo18.setContentAreaFilled(false);
        globo18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo18MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo18MouseReleased(evt);
            }
        });

        globo19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo19.png"))); // NOI18N
        globo19.setBorder(null);
        globo19.setBorderPainted(false);
        globo19.setContentAreaFilled(false);
        globo19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo19MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo19MouseReleased(evt);
            }
        });

        globo20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo20.png"))); // NOI18N
        globo20.setBorder(null);
        globo20.setBorderPainted(false);
        globo20.setContentAreaFilled(false);
        globo20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo20MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo20MouseReleased(evt);
            }
        });

        globo21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo21.png"))); // NOI18N
        globo21.setBorder(null);
        globo21.setBorderPainted(false);
        globo21.setContentAreaFilled(false);
        globo21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo21MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo21MouseReleased(evt);
            }
        });

        globo22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo22.png"))); // NOI18N
        globo22.setBorder(null);
        globo22.setBorderPainted(false);
        globo22.setContentAreaFilled(false);
        globo22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo22MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo22MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo22MouseReleased(evt);
            }
        });

        globo23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo23.png"))); // NOI18N
        globo23.setBorder(null);
        globo23.setBorderPainted(false);
        globo23.setContentAreaFilled(false);
        globo23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo23MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo23MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo23MouseReleased(evt);
            }
        });

        globo24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo24.png"))); // NOI18N
        globo24.setBorder(null);
        globo24.setBorderPainted(false);
        globo24.setContentAreaFilled(false);
        globo24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo24MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo24MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo24MouseReleased(evt);
            }
        });

        globo25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo25.png"))); // NOI18N
        globo25.setBorder(null);
        globo25.setBorderPainted(false);
        globo25.setContentAreaFilled(false);
        globo25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                globo25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                globo25MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                globo25MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                globo25MouseReleased(evt);
            }
        });

        titulo_password2.setForeground(new java.awt.Color(0, 0, 255));
        titulo_password2.setText("Introduce tu número de lista");
        titulo_password2.setFont(new java.awt.Font("PalMeMim", 1, 36)); // NOI18N

        boton_sonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton_sonido.png"))); // NOI18N
        boton_sonido.setBorderPainted(false);
        boton_sonido.setContentAreaFilled(false);
        boton_sonido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_sonidoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_sonidoMouseReleased(evt);
            }
        });

        back_pass_infantil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        back_pass_infantil.setBorderPainted(false);
        back_pass_infantil.setContentAreaFilled(false);

        home_pass_infantil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        home_pass_infantil.setBorderPainted(false);
        home_pass_infantil.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_sonido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(titulo_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(back_pass_infantil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(home_pass_infantil, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(globo3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(globo1)
                                                .addGap(33, 33, 33))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(globo9)
                                                .addGap(44, 44, 44)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(globo2)
                                            .addComponent(globo10))
                                        .addGap(48, 48, 48)
                                        .addComponent(globo11)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(globo4)
                                        .addGap(37, 37, 37)
                                        .addComponent(globo5)
                                        .addGap(48, 48, 48)
                                        .addComponent(globo6)
                                        .addGap(46, 46, 46)
                                        .addComponent(globo7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(globo12)
                                        .addGap(49, 49, 49)
                                        .addComponent(globo13)
                                        .addGap(58, 58, 58)
                                        .addComponent(globo14)
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(globo24)
                                            .addComponent(globo15))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(globo8)
                                    .addComponent(globo16)
                                    .addComponent(globo25)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(globo17)
                                .addGap(31, 31, 31)
                                .addComponent(globo18)
                                .addGap(30, 30, 30)
                                .addComponent(globo19)
                                .addGap(35, 35, 35)
                                .addComponent(globo20)
                                .addGap(44, 44, 44)
                                .addComponent(globo21)
                                .addGap(38, 38, 38)
                                .addComponent(globo22)
                                .addGap(29, 29, 29)
                                .addComponent(globo23)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_sonido))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(globo6)
                                    .addComponent(globo8)
                                    .addComponent(globo4)
                                    .addComponent(globo2))
                                .addGap(22, 22, 22))
                            .addComponent(globo1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(globo12))
                            .addComponent(globo10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(globo5)
                            .addComponent(globo7)
                            .addComponent(globo3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(globo9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(globo11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(globo14))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(globo15)
                                        .addComponent(globo13, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(globo16)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(globo17)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(globo22)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(globo23)
                            .addComponent(globo21))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(globo25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(globo18)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(globo19))
                                .addComponent(globo20)
                                .addComponent(globo24)))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_pass_infantil)
                    .addComponent(back_pass_infantil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void globo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo1MouseEntered
        globo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo1_hover.png")));
    }//GEN-LAST:event_globo1MouseEntered

    private void globo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo1MouseExited
        globo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo1.png")));
    }//GEN-LAST:event_globo1MouseExited

    private void globo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo1MousePressed
       globo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo1_press.png")));
    }//GEN-LAST:event_globo1MousePressed

    private void globo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo1MouseReleased
         globo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo1.png")));
    }//GEN-LAST:event_globo1MouseReleased

    private void globo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo2MouseEntered
        globo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo2_hover.png")));
    }//GEN-LAST:event_globo2MouseEntered

    private void globo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo2MouseExited
         globo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo2.png")));
    }//GEN-LAST:event_globo2MouseExited

    private void globo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo2MousePressed
        globo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo2_press.png")));
    }//GEN-LAST:event_globo2MousePressed

    private void globo2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo2MouseReleased
        globo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo2.png")));
    }//GEN-LAST:event_globo2MouseReleased

    private void globo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo3MouseEntered
        globo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo3_hover.png")));
    }//GEN-LAST:event_globo3MouseEntered

    private void globo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo3MouseExited
        globo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo3.png")));
    }//GEN-LAST:event_globo3MouseExited

    private void globo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo3MousePressed
       globo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo3_press.png")));
    }//GEN-LAST:event_globo3MousePressed

    private void globo3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo3MouseReleased
        globo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo3.png")));
    }//GEN-LAST:event_globo3MouseReleased

    private void globo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo4MouseEntered
        globo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo4_hover.png")));
    }//GEN-LAST:event_globo4MouseEntered

    private void globo4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo4MouseExited
        globo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo4.png")));
    }//GEN-LAST:event_globo4MouseExited

    private void globo4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo4MousePressed
        globo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo4_press.png")));
    }//GEN-LAST:event_globo4MousePressed

    private void globo4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo4MouseReleased
        globo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo4.png")));
    }//GEN-LAST:event_globo4MouseReleased

    private void globo5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo5MouseEntered
        globo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo5_hover.png")));
    }//GEN-LAST:event_globo5MouseEntered

    private void globo5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo5MouseExited
        globo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo5.png")));
    }//GEN-LAST:event_globo5MouseExited

    private void globo5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo5MousePressed
        globo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo5_press.png")));
    }//GEN-LAST:event_globo5MousePressed

    private void globo5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo5MouseReleased
        globo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo5.png")));
    }//GEN-LAST:event_globo5MouseReleased

    private void globo6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo6MouseEntered
        globo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo6_hover.png")));
    }//GEN-LAST:event_globo6MouseEntered

    private void globo6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo6MouseExited
        globo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo6.png")));
    }//GEN-LAST:event_globo6MouseExited

    private void globo6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo6MousePressed
        globo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo6_press.png")));
    }//GEN-LAST:event_globo6MousePressed

    private void globo6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo6MouseReleased
         globo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo6.png")));
    }//GEN-LAST:event_globo6MouseReleased

    private void globo7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo7MouseEntered
        globo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo7_hover.png")));
    }//GEN-LAST:event_globo7MouseEntered

    private void globo7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo7MouseExited
         globo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo7.png")));
    }//GEN-LAST:event_globo7MouseExited

    private void globo7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo7MousePressed
        globo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo7_press.png")));
    }//GEN-LAST:event_globo7MousePressed

    private void globo7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo7MouseReleased
        globo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo7.png")));
    }//GEN-LAST:event_globo7MouseReleased

    private void globo8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo8MouseEntered
        globo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo8_hover.png")));
    }//GEN-LAST:event_globo8MouseEntered

    private void globo8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo8MouseExited
        globo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo8.png")));
    }//GEN-LAST:event_globo8MouseExited

    private void globo8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo8MousePressed
        globo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo8_press.png")));
    }//GEN-LAST:event_globo8MousePressed

    private void globo8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo8MouseReleased
        globo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo8.png")));
    }//GEN-LAST:event_globo8MouseReleased

    private void globo9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo9MouseEntered
       globo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo9_hover.png")));
    }//GEN-LAST:event_globo9MouseEntered

    private void globo9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo9MouseExited
        globo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo9.png")));// TODO add your handling code here:
    }//GEN-LAST:event_globo9MouseExited

    private void globo9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo9MousePressed
        globo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo9_press.png")));
    }//GEN-LAST:event_globo9MousePressed

    private void globo9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo9MouseReleased
        globo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo9.png")));
    }//GEN-LAST:event_globo9MouseReleased

    private void globo10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo10MouseEntered
        globo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo10_hover.png")));
    }//GEN-LAST:event_globo10MouseEntered

    private void globo10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo10MouseExited
        globo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo10.png")));
    }//GEN-LAST:event_globo10MouseExited

    private void globo10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo10MousePressed
        globo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo10_press.png")));
    }//GEN-LAST:event_globo10MousePressed

    private void globo10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo10MouseReleased
        globo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo10.png")));
    }//GEN-LAST:event_globo10MouseReleased

    private void globo11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo11MouseEntered
        globo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo11_hover.png")));
    }//GEN-LAST:event_globo11MouseEntered

    private void globo11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo11MouseExited
        globo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo11.png")));
    }//GEN-LAST:event_globo11MouseExited

    private void globo11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo11MousePressed
       globo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo11_press.png")));
    }//GEN-LAST:event_globo11MousePressed

    private void globo11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo11MouseReleased
       globo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo11.png")));
    }//GEN-LAST:event_globo11MouseReleased

    private void globo12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo12MouseEntered
        globo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo12_hover.png")));
    }//GEN-LAST:event_globo12MouseEntered

    private void globo12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo12MouseExited
         globo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo12.png")));
    }//GEN-LAST:event_globo12MouseExited

    private void globo12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo12MousePressed
        globo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo12_press.png")));
    }//GEN-LAST:event_globo12MousePressed

    private void globo12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo12MouseReleased
        globo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo12.png")));
    }//GEN-LAST:event_globo12MouseReleased

    private void globo13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo13MouseEntered
       globo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo13_hover.png")));
    }//GEN-LAST:event_globo13MouseEntered

    private void globo13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo13MouseExited
         globo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo13.png")));
    }//GEN-LAST:event_globo13MouseExited

    private void globo13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo13MousePressed
        globo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo13_press.png")));
    }//GEN-LAST:event_globo13MousePressed

    private void globo13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo13MouseReleased
         globo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo13.png")));
    }//GEN-LAST:event_globo13MouseReleased

    private void globo14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo14MouseEntered
        globo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo14_hover.png")));
    }//GEN-LAST:event_globo14MouseEntered

    private void globo14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo14MouseExited
         globo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo14.png")));
    }//GEN-LAST:event_globo14MouseExited

    private void globo14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo14MousePressed
        globo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo14_press.png")));
    }//GEN-LAST:event_globo14MousePressed

    private void globo14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo14MouseReleased
         globo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo14.png")));
    }//GEN-LAST:event_globo14MouseReleased

    private void globo15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo15MouseEntered
        globo15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo15_hover.png")));
    }//GEN-LAST:event_globo15MouseEntered

    private void globo15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo15MouseExited
         globo15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo15.png")));
    }//GEN-LAST:event_globo15MouseExited

    private void globo15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo15MousePressed
        globo15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo15_press.png")));
    }//GEN-LAST:event_globo15MousePressed

    private void globo15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo15MouseReleased
         globo15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo15.png")));
    }//GEN-LAST:event_globo15MouseReleased

    private void globo16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo16MouseEntered
        globo16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo16_hover.png")));
    }//GEN-LAST:event_globo16MouseEntered

    private void globo16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo16MouseExited
         globo16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo16.png")));
    }//GEN-LAST:event_globo16MouseExited

    private void globo16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo16MousePressed
        globo16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo16_press.png")));
    }//GEN-LAST:event_globo16MousePressed

    private void globo16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo16MouseReleased
         globo16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo16.png")));
    }//GEN-LAST:event_globo16MouseReleased

    private void globo17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo17MouseEntered
        globo17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo17_hover.png")));
    }//GEN-LAST:event_globo17MouseEntered

    private void globo17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo17MouseExited
         globo17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo17.png")));
    }//GEN-LAST:event_globo17MouseExited

    private void globo17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo17MousePressed
        globo17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo17_press.png")));
    }//GEN-LAST:event_globo17MousePressed

    private void globo17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo17MouseReleased
         globo17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo17.png")));
    }//GEN-LAST:event_globo17MouseReleased

    private void globo18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo18MouseEntered
       globo18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo18_hover.png")));
    }//GEN-LAST:event_globo18MouseEntered

    private void globo18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo18MouseExited
         globo18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo18.png")));
    }//GEN-LAST:event_globo18MouseExited

    private void globo18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo18MousePressed
        globo18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo18_press.png")));
    }//GEN-LAST:event_globo18MousePressed

    private void globo18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo18MouseReleased
         globo18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo18.png")));
    }//GEN-LAST:event_globo18MouseReleased

    private void globo19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo19MouseEntered
        globo19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo19_hover.png")));
    }//GEN-LAST:event_globo19MouseEntered

    private void globo19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo19MouseExited
         globo19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo19.png")));
    }//GEN-LAST:event_globo19MouseExited

    private void globo19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo19MousePressed
        globo19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo19_press.png")));
    }//GEN-LAST:event_globo19MousePressed

    private void globo19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo19MouseReleased
         globo19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo19.png")));
    }//GEN-LAST:event_globo19MouseReleased

    private void globo20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo20MouseEntered
        globo20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo20_hover.png")));
    }//GEN-LAST:event_globo20MouseEntered

    private void globo20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo20MouseExited
         globo20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo20.png")));
    }//GEN-LAST:event_globo20MouseExited

    private void globo20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo20MousePressed
        globo20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo20_press.png")));
    }//GEN-LAST:event_globo20MousePressed

    private void globo20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo20MouseReleased
         globo20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo20.png")));
    }//GEN-LAST:event_globo20MouseReleased

    private void globo21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo21MouseEntered
        globo21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo21_hover.png")));
    }//GEN-LAST:event_globo21MouseEntered

    private void globo21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo21MouseExited
        globo21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo21.png")));
    }//GEN-LAST:event_globo21MouseExited

    private void globo21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo21MousePressed
        globo21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo21_press.png")));
    }//GEN-LAST:event_globo21MousePressed

    private void globo21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo21MouseReleased
        globo21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo21.png")));
    }//GEN-LAST:event_globo21MouseReleased

    private void globo22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo22MouseEntered
        globo22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo22_hover.png")));
    }//GEN-LAST:event_globo22MouseEntered

    private void globo22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo22MouseExited
        globo22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo22.png")));
    }//GEN-LAST:event_globo22MouseExited

    private void globo22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo22MousePressed
        globo22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo22_press.png")));
    }//GEN-LAST:event_globo22MousePressed

    private void globo22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo22MouseReleased
        globo22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo22.png")));
    }//GEN-LAST:event_globo22MouseReleased

    private void globo23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo23MouseEntered
        globo23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo23_hover.png")));
    }//GEN-LAST:event_globo23MouseEntered

    private void globo23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo23MouseExited
        globo23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo23.png")));
    }//GEN-LAST:event_globo23MouseExited

    private void globo23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo23MousePressed
       globo23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo23_press.png")));
    }//GEN-LAST:event_globo23MousePressed

    private void globo23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo23MouseReleased
       globo23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo23.png")));
    }//GEN-LAST:event_globo23MouseReleased

    private void globo24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo24MouseEntered
       globo24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo24_hover.png")));
    }//GEN-LAST:event_globo24MouseEntered

    private void globo24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo24MouseExited
        globo24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo24.png")));
    }//GEN-LAST:event_globo24MouseExited

    private void globo24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo24MousePressed
        globo24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo24_press.png")));
    }//GEN-LAST:event_globo24MousePressed

    private void globo24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo24MouseReleased
        globo24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo24.png")));
    }//GEN-LAST:event_globo24MouseReleased

    private void globo25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo25MouseEntered
        globo25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo25_hover.png")));
    }//GEN-LAST:event_globo25MouseEntered

    private void globo25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo25MouseExited
        globo25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo25.png")));
    }//GEN-LAST:event_globo25MouseExited

    private void globo25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo25MousePressed
        globo25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo25_press.png")));
    }//GEN-LAST:event_globo25MousePressed

    private void globo25MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globo25MouseReleased
       globo25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/globo25.png")));
    }//GEN-LAST:event_globo25MouseReleased

    private void boton_sonidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sonidoMousePressed
        /*if (musica_isActive) {
            boton_sonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton_sonido_pulsado.png")));
        } else {
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido_desactivado_pulsado.png")));
        }*/
    }//GEN-LAST:event_boton_sonidoMousePressed

    private void boton_sonidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sonidoMouseReleased
        /* if (musica_isActive) { //Si está activa -> la desactivamos.
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido_desactivado.png")));

            try {
                control.pause();
            } catch (BasicPlayerException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            boton_sonido.setIcon(new ImageIcon(getClass().getResource("/img/boton_sonido.png")));

            try {
                if (control_pausado) {
                    control.play();
                } else {
                    control.resume();
                }
                control_pausado = false;
            } catch (BasicPlayerException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(musica_isActive){
            musica_isActive = false;
        }else{
            musica_isActive = true;
        }*/
    }//GEN-LAST:event_boton_sonidoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_pass_infantil;
    private javax.swing.JButton boton_sonido;
    private javax.swing.JButton globo1;
    private javax.swing.JButton globo10;
    private javax.swing.JButton globo11;
    private javax.swing.JButton globo12;
    private javax.swing.JButton globo13;
    private javax.swing.JButton globo14;
    private javax.swing.JButton globo15;
    private javax.swing.JButton globo16;
    private javax.swing.JButton globo17;
    private javax.swing.JButton globo18;
    private javax.swing.JButton globo19;
    private javax.swing.JButton globo2;
    private javax.swing.JButton globo20;
    private javax.swing.JButton globo21;
    private javax.swing.JButton globo22;
    private javax.swing.JButton globo23;
    private javax.swing.JButton globo24;
    private javax.swing.JButton globo25;
    private javax.swing.JButton globo3;
    private javax.swing.JButton globo4;
    private javax.swing.JButton globo5;
    private javax.swing.JButton globo6;
    private javax.swing.JButton globo7;
    private javax.swing.JButton globo8;
    private javax.swing.JButton globo9;
    private javax.swing.JButton home_pass_infantil;
    private javax.swing.JPanel jPanel1;
    private com.alee.laf.label.WebLabel titulo_password2;
    // End of variables declaration//GEN-END:variables
}
