/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipo;

import JPanelsCustom.JPanelCustom;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import java.awt.Font;
import java.io.InputStream;
import java.awt.Dimension;


public class Password1 extends javax.swing.JFrame {

     Cursor mickey;
    Font font_titulos, font_subtitulos;
    String fontName = "/img/GinSSB60.ttf";
    Font font;
    ImageIcon fondo;
    
    
    public Password1() {
        
        Toolkit tk = getToolkit();
        ImageIcon imagen_cursor = new ImageIcon(getClass().getResource("/img/mano_mickey.png"));
        mickey = tk.createCustomCursor(imagen_cursor.getImage(), new Point(0, 0), "mickey");
        
        
          /*/ INICIO FUENTE
         /*/
        try {
            //Se carga la fuente
            InputStream is = getClass().getResourceAsStream(fontName);
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (Exception ex) {
            //Si existe un error se carga fuente por defecto ARIAL
            System.err.println(fontName + " No se cargo la fuente");
            font = new Font("Arial", Font.PLAIN, 14);
        }
        /*FIN FUENTE*/
        font_titulos = font.deriveFont(20f).deriveFont(1);
        font_subtitulos = font.deriveFont(40f).deriveFont(1);
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        letra1 = new javax.swing.JButton();
        letra2 = new javax.swing.JButton();
        letra3 = new javax.swing.JButton();
        letra4 = new javax.swing.JButton();
        letra5 = new javax.swing.JButton();
        letra6 = new javax.swing.JButton();
        letra7 = new javax.swing.JButton();
        letra8 = new javax.swing.JButton();
        letra9 = new javax.swing.JButton();
        letra10 = new javax.swing.JButton();
        letra11 = new javax.swing.JButton();
        letra12 = new javax.swing.JButton();
        letra13 = new javax.swing.JButton();
        letra14 = new javax.swing.JButton();
        letra15 = new javax.swing.JButton();
        letra16 = new javax.swing.JButton();
        letra17 = new javax.swing.JButton();
        letra18 = new javax.swing.JButton();
        letra19 = new javax.swing.JButton();
        letra20 = new javax.swing.JButton();
        letra21 = new javax.swing.JButton();
        letra22 = new javax.swing.JButton();
        letra23 = new javax.swing.JButton();
        letra24 = new javax.swing.JButton();
        letra25 = new javax.swing.JButton();
        letra26 = new javax.swing.JButton();
        letra27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_a.png"))); // NOI18N
        letra1.setBorder(null);
        letra1.setBorderPainted(false);
        letra1.setContentAreaFilled(false);
        letra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra1MouseReleased(evt);
            }
        });

        letra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_b.png"))); // NOI18N
        letra2.setBorder(null);
        letra2.setBorderPainted(false);
        letra2.setContentAreaFilled(false);
        letra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra2MouseReleased(evt);
            }
        });
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });

        letra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_c.png"))); // NOI18N
        letra3.setBorder(null);
        letra3.setBorderPainted(false);
        letra3.setContentAreaFilled(false);
        letra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra3MouseReleased(evt);
            }
        });
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });

        letra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_d.png"))); // NOI18N
        letra4.setBorder(null);
        letra4.setBorderPainted(false);
        letra4.setContentAreaFilled(false);
        letra4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra4MouseReleased(evt);
            }
        });

        letra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_e.png"))); // NOI18N
        letra5.setBorder(null);
        letra5.setBorderPainted(false);
        letra5.setContentAreaFilled(false);
        letra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra5MouseReleased(evt);
            }
        });

        letra6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_f.png"))); // NOI18N
        letra6.setBorder(null);
        letra6.setBorderPainted(false);
        letra6.setContentAreaFilled(false);
        letra6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra6MouseReleased(evt);
            }
        });

        letra7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_g.png"))); // NOI18N
        letra7.setBorder(null);
        letra7.setBorderPainted(false);
        letra7.setContentAreaFilled(false);
        letra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra7MouseReleased(evt);
            }
        });

        letra8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_h.png"))); // NOI18N
        letra8.setBorder(null);
        letra8.setBorderPainted(false);
        letra8.setContentAreaFilled(false);
        letra8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra8MouseReleased(evt);
            }
        });

        letra9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_i.png"))); // NOI18N
        letra9.setBorder(null);
        letra9.setBorderPainted(false);
        letra9.setContentAreaFilled(false);
        letra9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra9MouseReleased(evt);
            }
        });

        letra10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_j.png"))); // NOI18N
        letra10.setBorder(null);
        letra10.setBorderPainted(false);
        letra10.setContentAreaFilled(false);
        letra10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra10MouseReleased(evt);
            }
        });

        letra11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_k.png"))); // NOI18N
        letra11.setBorder(null);
        letra11.setBorderPainted(false);
        letra11.setContentAreaFilled(false);
        letra11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra11MouseReleased(evt);
            }
        });

        letra12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_l.png"))); // NOI18N
        letra12.setBorder(null);
        letra12.setBorderPainted(false);
        letra12.setContentAreaFilled(false);
        letra12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra12MouseReleased(evt);
            }
        });

        letra13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_m.png"))); // NOI18N
        letra13.setBorder(null);
        letra13.setBorderPainted(false);
        letra13.setContentAreaFilled(false);
        letra13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra13MouseReleased(evt);
            }
        });

        letra14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_n.png"))); // NOI18N
        letra14.setBorder(null);
        letra14.setBorderPainted(false);
        letra14.setContentAreaFilled(false);
        letra14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra14MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra14MouseReleased(evt);
            }
        });

        letra15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_nn.png"))); // NOI18N
        letra15.setBorder(null);
        letra15.setBorderPainted(false);
        letra15.setContentAreaFilled(false);
        letra15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra15MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra15MouseReleased(evt);
            }
        });

        letra16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_o.png"))); // NOI18N
        letra16.setBorder(null);
        letra16.setBorderPainted(false);
        letra16.setContentAreaFilled(false);
        letra16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra16MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra16MouseReleased(evt);
            }
        });

        letra17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_p.png"))); // NOI18N
        letra17.setBorder(null);
        letra17.setBorderPainted(false);
        letra17.setContentAreaFilled(false);
        letra17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra17MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra17MouseReleased(evt);
            }
        });

        letra18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_q.png"))); // NOI18N
        letra18.setBorder(null);
        letra18.setBorderPainted(false);
        letra18.setContentAreaFilled(false);
        letra18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra18MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra18MouseReleased(evt);
            }
        });

        letra19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_r.png"))); // NOI18N
        letra19.setBorder(null);
        letra19.setBorderPainted(false);
        letra19.setContentAreaFilled(false);
        letra19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra19MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra19MouseReleased(evt);
            }
        });

        letra20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_s.png"))); // NOI18N
        letra20.setBorder(null);
        letra20.setBorderPainted(false);
        letra20.setContentAreaFilled(false);
        letra20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra20MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra20MouseReleased(evt);
            }
        });

        letra21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_t.png"))); // NOI18N
        letra21.setBorder(null);
        letra21.setBorderPainted(false);
        letra21.setContentAreaFilled(false);
        letra21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra21MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra21MouseReleased(evt);
            }
        });

        letra22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_u.png"))); // NOI18N
        letra22.setBorder(null);
        letra22.setBorderPainted(false);
        letra22.setContentAreaFilled(false);
        letra22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra22MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra22MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra22MouseReleased(evt);
            }
        });

        letra23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_v.png"))); // NOI18N
        letra23.setBorder(null);
        letra23.setBorderPainted(false);
        letra23.setContentAreaFilled(false);
        letra23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra23MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra23MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra23MouseReleased(evt);
            }
        });

        letra24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_w.png"))); // NOI18N
        letra24.setBorder(null);
        letra24.setBorderPainted(false);
        letra24.setContentAreaFilled(false);
        letra24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra24MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra24MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra24MouseReleased(evt);
            }
        });

        letra25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_x.png"))); // NOI18N
        letra25.setBorder(null);
        letra25.setBorderPainted(false);
        letra25.setContentAreaFilled(false);
        letra25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra25MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra25MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra25MouseReleased(evt);
            }
        });

        letra26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_y.png"))); // NOI18N
        letra26.setBorder(null);
        letra26.setBorderPainted(false);
        letra26.setContentAreaFilled(false);
        letra26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra26MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra26MouseReleased(evt);
            }
        });

        letra27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_z.png"))); // NOI18N
        letra27.setBorder(null);
        letra27.setBorderPainted(false);
        letra27.setContentAreaFilled(false);
        letra27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                letra27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                letra27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra27MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                letra27MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(letra1)
                .addContainerGap(703, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(letra2)
                    .addContainerGap(693, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(letra3)
                    .addContainerGap(683, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(letra4)
                    .addContainerGap(673, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(letra5)
                    .addContainerGap(663, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(letra6)
                    .addContainerGap(653, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(letra7)
                    .addContainerGap(643, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(letra8)
                    .addContainerGap(633, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(letra9)
                    .addContainerGap(623, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(letra10)
                    .addContainerGap(613, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(letra11)
                    .addContainerGap(603, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(letra12)
                    .addContainerGap(593, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(letra13)
                    .addContainerGap(583, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(letra14)
                    .addContainerGap(573, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(letra15)
                    .addContainerGap(563, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addComponent(letra16)
                    .addContainerGap(553, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(letra17)
                    .addContainerGap(543, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(letra18)
                    .addContainerGap(533, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(letra19)
                    .addContainerGap(523, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(letra20)
                    .addContainerGap(513, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(letra21)
                    .addContainerGap(503, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(letra22)
                    .addContainerGap(493, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(letra23)
                    .addContainerGap(483, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(letra24)
                    .addContainerGap(473, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(286, 286, 286)
                    .addComponent(letra25)
                    .addContainerGap(463, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addComponent(letra26)
                    .addContainerGap(453, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(306, 306, 306)
                    .addComponent(letra27)
                    .addContainerGap(443, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(letra1)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(letra2)
                    .addContainerGap(384, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(letra3)
                    .addContainerGap(374, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(letra4)
                    .addContainerGap(364, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(195, 195, 195)
                    .addComponent(letra5)
                    .addContainerGap(354, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(letra6)
                    .addContainerGap(344, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(letra7)
                    .addContainerGap(334, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(225, 225, 225)
                    .addComponent(letra8)
                    .addContainerGap(324, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(235, 235, 235)
                    .addComponent(letra9)
                    .addContainerGap(314, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(letra10)
                    .addContainerGap(304, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addComponent(letra11)
                    .addContainerGap(294, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(265, 265, 265)
                    .addComponent(letra12)
                    .addContainerGap(284, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(275, 275, 275)
                    .addComponent(letra13)
                    .addContainerGap(274, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(285, Short.MAX_VALUE)
                    .addComponent(letra14)
                    .addGap(264, 264, 264)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(295, Short.MAX_VALUE)
                    .addComponent(letra15)
                    .addGap(254, 254, 254)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(305, Short.MAX_VALUE)
                    .addComponent(letra16)
                    .addGap(244, 244, 244)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(letra17)
                    .addGap(234, 234, 234)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(325, Short.MAX_VALUE)
                    .addComponent(letra18)
                    .addGap(224, 224, 224)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(335, Short.MAX_VALUE)
                    .addComponent(letra19)
                    .addGap(214, 214, 214)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(345, Short.MAX_VALUE)
                    .addComponent(letra20)
                    .addGap(204, 204, 204)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(355, Short.MAX_VALUE)
                    .addComponent(letra21)
                    .addGap(194, 194, 194)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(365, Short.MAX_VALUE)
                    .addComponent(letra22)
                    .addGap(184, 184, 184)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(375, Short.MAX_VALUE)
                    .addComponent(letra23)
                    .addGap(174, 174, 174)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(385, Short.MAX_VALUE)
                    .addComponent(letra24)
                    .addGap(164, 164, 164)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(395, Short.MAX_VALUE)
                    .addComponent(letra25)
                    .addGap(154, 154, 154)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(405, Short.MAX_VALUE)
                    .addComponent(letra26)
                    .addGap(144, 144, 144)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(415, Short.MAX_VALUE)
                    .addComponent(letra27)
                    .addGap(134, 134, 134)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MouseEntered
        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_a_hover.png")));
    }//GEN-LAST:event_letra1MouseEntered

    private void letra1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MouseExited
        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_a.png")));
    }//GEN-LAST:event_letra1MouseExited

    private void letra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MousePressed
        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_a_press.png")));
    }//GEN-LAST:event_letra1MousePressed

    private void letra1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MouseReleased
        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_a.png")));
    }//GEN-LAST:event_letra1MouseReleased

    private void letra2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MouseEntered
        letra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_b_hover.png")));
    }//GEN-LAST:event_letra2MouseEntered

    private void letra2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MouseExited
        letra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_b.png")));
    }//GEN-LAST:event_letra2MouseExited

    private void letra2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MousePressed
        letra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_b_press.png")));
    }//GEN-LAST:event_letra2MousePressed

    private void letra2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MouseReleased
       letra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_b.png")));
    }//GEN-LAST:event_letra2MouseReleased

    private void letra3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MouseEntered
        letra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_c_hover.png")));
    }//GEN-LAST:event_letra3MouseEntered

    private void letra3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MouseExited
        letra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_c.png")));
    }//GEN-LAST:event_letra3MouseExited

    private void letra3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MousePressed
        letra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_c_press.png")));
    }//GEN-LAST:event_letra3MousePressed

    private void letra3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MouseReleased
        letra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_c.png")));
    }//GEN-LAST:event_letra3MouseReleased

    private void letra4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MouseEntered
        letra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_d_hover.png")));
    }//GEN-LAST:event_letra4MouseEntered

    private void letra4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MouseExited
        letra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_d.png")));
    }//GEN-LAST:event_letra4MouseExited

    private void letra4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MousePressed
        letra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_d_press.png")));
    }//GEN-LAST:event_letra4MousePressed

    private void letra4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MouseReleased
        letra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_d.png")));
    }//GEN-LAST:event_letra4MouseReleased

    private void letra5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MouseEntered
         letra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_e_hover.png")));
    }//GEN-LAST:event_letra5MouseEntered

    private void letra5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MouseExited
        letra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_e.png")));
    }//GEN-LAST:event_letra5MouseExited

    private void letra5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MousePressed
        letra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_e_press.png")));
    }//GEN-LAST:event_letra5MousePressed

    private void letra5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MouseReleased
        letra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_e.png")));
    }//GEN-LAST:event_letra5MouseReleased

    private void letra6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MouseEntered
         letra6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_f_hover.png")));
    }//GEN-LAST:event_letra6MouseEntered

    private void letra6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MouseExited
        letra6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_f.png")));
    }//GEN-LAST:event_letra6MouseExited

    private void letra6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MousePressed
        letra6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_f_press.png")));
    }//GEN-LAST:event_letra6MousePressed

    private void letra6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MouseReleased
        letra6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_f.png")));
    }//GEN-LAST:event_letra6MouseReleased

    private void letra7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MouseEntered
          letra7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_g_hover.png")));
    }//GEN-LAST:event_letra7MouseEntered

    private void letra7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MouseExited
         letra7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_g.png")));
    }//GEN-LAST:event_letra7MouseExited

    private void letra7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MousePressed
         letra7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_g_press.png")));
    }//GEN-LAST:event_letra7MousePressed

    private void letra7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MouseReleased
       letra7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_g.png")));
    }//GEN-LAST:event_letra7MouseReleased

    private void letra8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MouseEntered
         letra8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_h_hover.png")));
    }//GEN-LAST:event_letra8MouseEntered

    private void letra8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MouseExited
        letra8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_h.png")));
    }//GEN-LAST:event_letra8MouseExited

    private void letra8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MousePressed
        letra8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_h_press.png")));
    }//GEN-LAST:event_letra8MousePressed

    private void letra8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MouseReleased
       letra8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_h.png")));
    }//GEN-LAST:event_letra8MouseReleased

    private void letra9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MouseEntered
        letra9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_i:hover.png")));
    }//GEN-LAST:event_letra9MouseEntered

    private void letra9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MouseExited
        letra9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_i.png")));
    }//GEN-LAST:event_letra9MouseExited

    private void letra9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MousePressed
      letra9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_i_press.png")));
    }//GEN-LAST:event_letra9MousePressed

    private void letra9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MouseReleased
       letra9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_i.png")));
    }//GEN-LAST:event_letra9MouseReleased

    private void letra10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MouseEntered
           letra10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_j_hover.png")));
    }//GEN-LAST:event_letra10MouseEntered

    private void letra10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MouseExited
            letra10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_j.png")));
    }//GEN-LAST:event_letra10MouseExited

    private void letra10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MousePressed
             letra10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_j_press.png")));
    }//GEN-LAST:event_letra10MousePressed

    private void letra10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MouseReleased
            letra10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_j.png")));
    }//GEN-LAST:event_letra10MouseReleased

    private void letra11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MouseEntered
          letra11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_k_hover.png")));
    }//GEN-LAST:event_letra11MouseEntered

    private void letra11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MouseExited
        letra11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_k.png")));
    }//GEN-LAST:event_letra11MouseExited

    private void letra11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MousePressed
        letra11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_k_press.png")));
    }//GEN-LAST:event_letra11MousePressed

    private void letra11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MouseReleased
       letra11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_k.png")));
    }//GEN-LAST:event_letra11MouseReleased

    private void letra12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MouseEntered
        letra12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_l_hover.png")));
    }//GEN-LAST:event_letra12MouseEntered

    private void letra12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MouseExited
        letra12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_l.png")));
    }//GEN-LAST:event_letra12MouseExited

    private void letra12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MousePressed
      letra12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_l_press.png")));
    }//GEN-LAST:event_letra12MousePressed

    private void letra12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MouseReleased
         letra12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_l.png")));
    }//GEN-LAST:event_letra12MouseReleased

    private void letra13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MouseEntered
        letra13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_m_hover.png")));
    }//GEN-LAST:event_letra13MouseEntered

    private void letra13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MouseExited
        letra13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_m.png")));
    }//GEN-LAST:event_letra13MouseExited

    private void letra13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MousePressed
         letra13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_m_press.png")));
    }//GEN-LAST:event_letra13MousePressed

    private void letra13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MouseReleased
        letra13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_m.png")));
    }//GEN-LAST:event_letra13MouseReleased

    private void letra14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MouseEntered
         letra14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_n_hover.png")));
    }//GEN-LAST:event_letra14MouseEntered

    private void letra14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MouseExited
        letra14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_n.png")));
    }//GEN-LAST:event_letra14MouseExited

    private void letra14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MousePressed
        letra14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_n_press.png")));
    }//GEN-LAST:event_letra14MousePressed

    private void letra14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MouseReleased
        letra14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_n.png")));
    }//GEN-LAST:event_letra14MouseReleased

    private void letra15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MouseEntered
        letra15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_nn_hover.png")));
    }//GEN-LAST:event_letra15MouseEntered

    private void letra15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MouseExited
         letra15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_nn.png")));
    }//GEN-LAST:event_letra15MouseExited

    private void letra15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MousePressed
         letra15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_nn_press.png")));
    }//GEN-LAST:event_letra15MousePressed

    private void letra15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MouseReleased
         letra15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_nn.png")));
    }//GEN-LAST:event_letra15MouseReleased

    private void letra16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MouseEntered
        letra16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_o_hover.png")));
    }//GEN-LAST:event_letra16MouseEntered

    private void letra16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MouseExited
        letra16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_o.png")));
    }//GEN-LAST:event_letra16MouseExited

    private void letra16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MousePressed
        letra16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_o_press.png")));
    }//GEN-LAST:event_letra16MousePressed

    private void letra16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MouseReleased
        letra16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_o.png")));
    }//GEN-LAST:event_letra16MouseReleased

    private void letra17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MouseEntered
        letra17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_p_hover.png")));
    }//GEN-LAST:event_letra17MouseEntered

    private void letra17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MouseExited
         letra17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_p.png")));
    }//GEN-LAST:event_letra17MouseExited

    private void letra17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MousePressed
         letra17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_p_press.png")));
    }//GEN-LAST:event_letra17MousePressed

    private void letra17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MouseReleased
         letra17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_p.png")));
    }//GEN-LAST:event_letra17MouseReleased

    private void letra18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MouseEntered
         letra18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_q_hover.png")));
    }//GEN-LAST:event_letra18MouseEntered

    private void letra18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MouseExited
        letra18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_q.png")));
    }//GEN-LAST:event_letra18MouseExited

    private void letra18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MousePressed
        letra18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_q_press.png")));
    }//GEN-LAST:event_letra18MousePressed

    private void letra18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MouseReleased
        letra18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_q.png")));
    }//GEN-LAST:event_letra18MouseReleased

    private void letra19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MouseEntered
        letra19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_r_hover.png")));
    }//GEN-LAST:event_letra19MouseEntered

    private void letra19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MouseExited
        letra19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_r.png")));
    }//GEN-LAST:event_letra19MouseExited

    private void letra19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MousePressed
        letra19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_r_hover.png")));
    }//GEN-LAST:event_letra19MousePressed

    private void letra19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MouseReleased
        letra19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_r.png")));
    }//GEN-LAST:event_letra19MouseReleased

    private void letra20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MouseEntered
        letra20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_s_hover.png")));
    }//GEN-LAST:event_letra20MouseEntered

    private void letra20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MouseExited
        letra20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_s.png")));
    }//GEN-LAST:event_letra20MouseExited

    private void letra20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MousePressed
        letra20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_s_press.png")));
    }//GEN-LAST:event_letra20MousePressed

    private void letra20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MouseReleased
       letra20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_s.png")));
    }//GEN-LAST:event_letra20MouseReleased

    private void letra21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MouseEntered
        letra21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_t_hover.png")));
    }//GEN-LAST:event_letra21MouseEntered

    private void letra21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MouseExited
        letra21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_t.png")));
    }//GEN-LAST:event_letra21MouseExited

    private void letra21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MousePressed
        letra21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_t_press.png")));
    }//GEN-LAST:event_letra21MousePressed

    private void letra21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MouseReleased
        letra21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_t.png")));
    }//GEN-LAST:event_letra21MouseReleased

    private void letra22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MouseEntered
        letra22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_u_hover.png")));
    }//GEN-LAST:event_letra22MouseEntered

    private void letra22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MouseExited
         letra22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_u.png")));
    }//GEN-LAST:event_letra22MouseExited

    private void letra22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MousePressed
        letra22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_u_press.png")));
    }//GEN-LAST:event_letra22MousePressed

    private void letra22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MouseReleased
         letra22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_u.png")));
    }//GEN-LAST:event_letra22MouseReleased

    private void letra23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MouseEntered
         letra23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_v_hover.png")));
    }//GEN-LAST:event_letra23MouseEntered

    private void letra23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MouseExited
        letra23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_v.png")));
    }//GEN-LAST:event_letra23MouseExited

    private void letra23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MousePressed
        letra23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_v_press.png")));
    }//GEN-LAST:event_letra23MousePressed

    private void letra23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MouseReleased
       letra23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_v.png")));
    }//GEN-LAST:event_letra23MouseReleased

    private void letra24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MouseEntered
       letra24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_w_hover.png")));
    }//GEN-LAST:event_letra24MouseEntered

    private void letra24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MouseExited
        letra24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_w.png")));
    }//GEN-LAST:event_letra24MouseExited

    private void letra24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MousePressed
        letra24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_w_press.png")));
    }//GEN-LAST:event_letra24MousePressed

    private void letra24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MouseReleased
       letra24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_w.png")));
    }//GEN-LAST:event_letra24MouseReleased

    private void letra25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MouseEntered
        letra25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_x_hover.png")));
    }//GEN-LAST:event_letra25MouseEntered

    private void letra25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MouseExited
        letra25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_x.png")));
    }//GEN-LAST:event_letra25MouseExited

    private void letra25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MousePressed
       letra25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_x_press.png")));
    }//GEN-LAST:event_letra25MousePressed

    private void letra25MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MouseReleased
        letra25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_x.png")));
    }//GEN-LAST:event_letra25MouseReleased

    private void letra26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MouseEntered
        letra26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_y_hover.png")));
    }//GEN-LAST:event_letra26MouseEntered

    private void letra26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MouseExited
        letra26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_y.png")));
    }//GEN-LAST:event_letra26MouseExited

    private void letra26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MousePressed
        letra26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_y_press.png")));
    }//GEN-LAST:event_letra26MousePressed

    private void letra26MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MouseReleased
        letra26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_y.png")));
    }//GEN-LAST:event_letra26MouseReleased

    private void letra27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MouseEntered
       letra27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_z_hover.png")));
    }//GEN-LAST:event_letra27MouseEntered

    private void letra27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MouseExited
       letra27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_z.png")));
    }//GEN-LAST:event_letra27MouseExited

    private void letra27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MousePressed
        letra27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_z_press.png")));
    }//GEN-LAST:event_letra27MousePressed

    private void letra27MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MouseReleased
        letra27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letras_z.png")));
    }//GEN-LAST:event_letra27MouseReleased

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra2ActionPerformed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton letra1;
    private javax.swing.JButton letra10;
    private javax.swing.JButton letra11;
    private javax.swing.JButton letra12;
    private javax.swing.JButton letra13;
    private javax.swing.JButton letra14;
    private javax.swing.JButton letra15;
    private javax.swing.JButton letra16;
    private javax.swing.JButton letra17;
    private javax.swing.JButton letra18;
    private javax.swing.JButton letra19;
    private javax.swing.JButton letra2;
    private javax.swing.JButton letra20;
    private javax.swing.JButton letra21;
    private javax.swing.JButton letra22;
    private javax.swing.JButton letra23;
    private javax.swing.JButton letra24;
    private javax.swing.JButton letra25;
    private javax.swing.JButton letra26;
    private javax.swing.JButton letra27;
    private javax.swing.JButton letra3;
    private javax.swing.JButton letra4;
    private javax.swing.JButton letra5;
    private javax.swing.JButton letra6;
    private javax.swing.JButton letra7;
    private javax.swing.JButton letra8;
    private javax.swing.JButton letra9;
    // End of variables declaration//GEN-END:variables
}
